kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: demo-service2-product
  name: demo-service2-product 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service2-product
  template:
    metadata:
      name: demo-service2-product
      labels:
        app: demo-service2-product
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - demo-service2-product
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: demo-service2-product
        image: repository:5000/demo-service2-product:<VERSION>
        imagePullPolicy: Always
        env:
          - name: GIT_URL
            value: "http://demo-service-config:9000"
          - name: SW_AGENT_NAME
            value: "demo-service2-product"
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "skywalking:11800"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service2-product
  name: demo-service2-product
  namespace: default
spec:
  ports:
  - port: 9003 
    targetPort: 9003
  selector:
    app: demo-service2-product
